# Generated by Django 2.1.7 on 2019-03-16 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_author_book_bookauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adverts.Book'),
        ),
    ]
