# Generated by Django 2.1.7 on 2019-03-17 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_advert_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookauthor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookauthor',
            name='book',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookAuthor',
        ),
    ]
