# Generated by Django 2.1.7 on 2019-03-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0005_auto_20190317_0439'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
